# Generated by Django 3.2.4 on 2021-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=100)),
                ('notify', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=10)),
            ],
        ),
    ]
